### ISSUE TITLE
tensorflow error

### ISSUE THREAD

**Issue by abdo-fysal** [victordibia/handtracking#11]
ValueError: No op named NonMaxSuppressionV2 in defined operations.

**Comment by abdo-fysal** [comment]
thanks for reply,i change tensorflow version to 1.4..0-rc0 , but another error appeared
InvalidArgumentError (see above for traceback): NodeDef mentions attr 'T' not in Op<name=Where; signature=input:bool -> index:int64>; NodeDef: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Where = Where[T=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Where/Cast). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Where = Where[T=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Postprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/FilterGreaterThan/Where/Cast)]]

**Comment by victordibia** [comment]
Hi @abdo-fysal ,

This error has been discussed in issue #1 .
The solution there was to generate the frozen model graph from the checkpoint files I provide in the repo. Please try that.

-V.
