### ISSUE TITLE
the detected box is wrong

### ISSUE THREAD

**Issue by qingzew** [victordibia/handtracking#13]
os: mac
tf: 1.4.0-rc0
when I run `detect_single_threaded.py`, the detected box going wrong, like https://github.com/victordibia/handtracking/issues/1 @victordibia mentioned, but tf is not 1.4.1
![](https://user-images.githubusercontent.com/1547007/33856223-75008ec6-de95-11e7-9718-f5cdca869d12.gif)

**Comment by victordibia** [comment]
Hi @qingzew 

Did you export the frozen graph using your tensorflow verssion as suggested in issue #1  ?
I get correct results when I do this.

-V.

**Comment by qingzew** [comment]
@victordibia yes, I did it, but still wrong, could you provide your training enviroment?

**Comment by qingzew** [comment]
I retrain the model using tensorflow 1.6.0, everything is ok

**Comment by jimniDev** [comment]
Hi @qingzew
I think iI'm now going through similar detection error because of tensorflow version.
(I'm currently using 2.2 verison). I'm considering retain the model since i found out your issue.
Can I ask how did u retrain the model?
Is it just the same process explained in readme.md?
