### ISSUE TITLE
Set up model

### ISSUE THREAD

**Issue by svebert** [victordibia/handtracking#17]
Hi!
Could you also release the scripts for building the initial model?
Actually, I have no clue how to make a tensorflow model from the ssd_mobilenet_v1_coco.config.

What I got is reading all trainable variables from the model.ckpt file:
```
import tensorflow as tf
MODEL_DIR = 'C:/MYPATH/'
MODEL_NAME = 'model.ckpt-200002'
MODEL_NAME_OUTPUT = 'raw_ssd_mobilenet_v1_coco'
with tf.Session() as sess:
	new_saver = tf.train.import_meta_graph(MODEL_DIR + '/' + MODEL_NAME + '.meta')

#get all variables
tf_variables = tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES)

f = open(MODEL_NAME_OUTPUT+'_vars.txt','w')

for var in tf_variables:
	var_name= var.name
	var_dtype = var.dtype
	var_shape = var.shape
	f.write(str(var_name)+"\t"+str(var_dtype)+"\t"+str(var_shape)+"\n")
f.close()
```

from that I could rebuild most of the ANN but now, I am stuck at the BoxPredictor-Layers. It is hard to figure out what they are and what their input layers are. 

Any hints?

My aim is to rebuild the net in Caffee, but I can not figure out the exact detailed layer-structure from tensorflow.

**Comment by victordibia** [comment]
Hi,

The initial ssd + MobileNet model is provided by the tensorflow object detection api. I’d say you take a look at the tensorflow object detection api repo. 

V.
