### ISSUE TITLE
How to train?

### ISSUE THREAD

**Issue by ldenoue** [victordibia/handtracking#18]
Could you point us to how to train on our own images? The article and readme files only seem to talk about inference, but no training: how can we perform the transfer learning and retrain with our own images like you did?
Thanks!

**Comment by victordibia** [comment]
Hi @ldenoue ,

There were a few article that already did an excellent job of demonstrating the training process.  I actually followed them in training the hand model.

> **Training on your own images**: Please use the [guide provided by Harrison from pythonprogramming](https://pythonprogramming.net/training-custom-objects-tensorflow-object-detection-api-tutorial/) on how to generate tfrecords given your label csv files and your images. The guide also covers how to start the training process if training locally. [see [here] (https://pythonprogramming.net/training-custom-objects-tensorflow-object-detection-api-tutorial/)]. If training in the cloud using a service like GCP, see the [guide here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_cloud.md).

Also see this excellent article from Dat Tran - https://towardsdatascience.com/how-to-train-your-own-object-detector-with-tensorflows-object-detector-api-bec72ecfe1d9 .

-V
