### ISSUE TITLE
Any suggest about improving different viewpoint detection performance with additional data？

### ISSUE THREAD

**Issue by ZhaoWangFu** [victordibia/handtracking#2]
Hi, There! Thanks for your share first! I want to detected hands under both egocentric and non-egocentric viewpoints, so i planned to add some new data to the existing Egohands Dataset before training, were there something i have to take into consider? eg, newly added image should be the same size with images in Egohands Dataset? The number of newly added non-egocentric images should be comparable
to those in Egohands Dataset? And other factors that was import.

**Comment by victordibia** [comment]
Great question!

I honestly do not know enough to give a confident answer as I have not run many similar experiments. However, my intuition is that if your dataset contains vastly different images (e.g the hands in some samples differ greatly from the hands in others) for same class, the network may have a hard time learning the right features that capture `all` of the data. This might mean the network may take longer to train and the final loss values may not be very low (or indicate a failure to converge).  
From this point of view, it may be useful to have similar image size/resolution/quality. The more the data the better, so having comparable or more `non-egocentric` data should yield good results.

I would say you run some experiments and please share the results if you can!
-V.

**Comment by ZhaoWangFu** [comment]
OK, I will try!
