### ISSUE TITLE
Comparison with YOLO on the same dataset

### ISSUE THREAD

**Issue by srp-31** [victordibia/handtracking#25]
Hi Victor and others,

Has anyone trained the recent yolo(v1 v2 or v3) on the ego hands dataset and can probile provide a absic comparison in terms of speed and accuracy?

thanks in advanace
shreeraman

**Comment by victordibia** [comment]
Hi @srp-31 ,

There is a paper I reference in the blog post where researchers have done a comparison of ssd and yolo on a basic dataset for the object detection task. 

[http://arxiv.org/abs/1611.10012](
http://arxiv.org/abs/1611.10012)

[1] J. Huang, V. Rathod, C. Sun, M. Zhu, A. Korattikara, A. Fathi, I. Fischer, Z. Wojna, Y. Song, S. Guadarrama, and K. Murphy, “Speed/accuracy trade-offs for modern convolutional object detectors,” in IEEE CVPR, 2017, pp. 1–21.

**Comment by srp-31** [comment]
Hi Victor

Thank you for the speedy reply. I was looking for it all over and somehow missed it.

thanks a lot.

**Comment by srp-31** [comment]
Hi Victor

Thank you for the speedy reply. I was looking for it all over and somehow missed it. 

I closed it thinking it might have a comparison with yolo. But unfortunately this paper does not deal with yolo. 
There is however already some work in thsi regards:-

http://cs231n.stanford.edu/reports/2017/posters/225.pdf

I am going to try and get in touch with them. I will update on the issue about my progress.

thanks a lot.

shreeraman

**Comment by ghffarpk** [comment]
Hi srp-31, I am also training a yolo model by using this dataset. Have you got success in it ?

**Comment by srp-31** [comment]
Hi ghffarpk,

I suspended training yolo since the resutls form victor's code meets my requirement. I will update you if I train yolo for the dataset.

goodluck.
