### ISSUE TITLE
How to save output video?

### ISSUE THREAD

**Issue by JasOlean** [victordibia/handtracking#27]
Dear Sir,

I would like to use the detected hand bounding box in the scene to the next step. So, how to save the value of these detected bounding box to feed to next step? 
I would like to save detected bounding box value in real time and would like to save output video file with detection.

**Comment by victordibia** [comment]
There are several ways to do this.
The code outputs an image frame on which annotations have been drawn. You can write these frames to a folder and then covert it into a video. Or you convert frames to an array which is then converted to a video.

For both approaches, you can [use OpenCV tools ](https://stackoverflow.com/questions/51914683/how-to-make-video-from-an-updating-numpy-array-in-python) or libraries like [imagio](https://imageio.readthedocs.io/en/latest/userapi.html).
