### ISSUE TITLE
Keypoints regression

### ISSUE THREAD

**Issue by pharrellyhy** [victordibia/handtracking#31]
Hi, Victor

Can we add additional feature, like hand keypoints regression when detecting the hand? If so, how? I want to do hand pose detection. Thanks.

**Comment by victordibia** [comment]
Hi @pharrellyhy ,

Our training samples do not have any hand post data, so this will be hard to do ...
For keypoint regression, we need to first annotate data on keypoints or a specific set of poses and then train the model.

Victor.
