### ISSUE TITLE
How to get you mAP?

### ISSUE THREAD

**Issue by JensenGao** [victordibia/handtracking#37]
Excuse me.
I want konw how do you get your mAP?
I eval my model with objection_datection/eval.py, but I can't get the value.
Hope you can tell me, thank you.

**Comment by victordibia** [comment]
Information on mAP can be obtained in tensorboard.
During training, you can run an eval process and point tensorboard to the checkpoint directory. 
See instructions [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_cloud.md#running-an-evaluation-job-on-cmle).
