### ISSUE TITLE
TypeError: Descriptors should not be created directly, but only retrieved from their parent.

### ISSUE THREAD

**Issue by keshavoct98** [victordibia/handtracking#38]
I am using tensorflow 1.9.0 and I am getting an error while executing the below given command in anaconda prompt_
python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config

Here's the error_
Traceback (most recent call last):
  File "train.py", line 44, in <module>
    options=None),
  File "C:\Users\keshav\Anaconda3\envs\neuralnets\lib\site-packages\google\protobuf\descriptor.py", line 530, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors should not be created directly, but only retrieved from their parent.

**Comment by victordibia** [comment]
This looks like a protobuf version problem.
Ensure you have protobuf and all other obj detection api dependencies installed. https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/installation.md

See discussion here : https://github.com/ethereon/caffe-tensorflow/issues/114
