### ISSUE TITLE
Can this model distinguish left hands and right hands?

### ISSUE THREAD

**Issue by momo1986** [victordibia/handtracking#41]
Can this model distinguish the left hand and right hand?
For my application, I need to handle this issue.

**Comment by momo1986** [comment]
Is there method that I can distinguish the left hand and right hand from the image train label with different patterns?

**Comment by victordibia** [comment]
Yes. If you retrain the model and use the Egohands dataset label for left and right hand, you can train the model to distinguish left and right hand. 
See the dataset section of the [readme](https://github.com/victordibia/handtracking#data-preparation-and-network-training-in-tensorflow-dataset-import-training) and the [cleaning script below.
](https://github.com/victordibia/handtracking/blob/master/egohands_dataset_clean.py)
