### ISSUE TITLE
Do I have to modify the detect_utils.py?

### ISSUE THREAD

**Issue by hamny88** [victordibia/handtracking#44]
Hi i'm trying to use your handtracking model, and I'm beginner of Tensorflow.
I started follow your repo from the 'Using Hand Detector'... and I executed detector_utils.py
`python3 detector_utils.py`
And I have an error like this. 
`Traceback (most recent call last):
  File "detector_utils.py", line 10, in <module>
    from utils import label_map_util
ModuleNotFoundError: No module named 'utils'
`
I run this code in 
`~/venv/lib/python3.6/site-packages/tensorflow/models/research/handtracking-master/utils` 
I installed Object_detection already.
I wonder do I have to modify the `sys.path.append("..")` part in detector_utils.py ?
If I have to do, then What path should be in there? 

I have googled about it for a long time, but still have a problem 
How can I solve it?

**Comment by InderdeepBajwa** [comment]
Nope. You gotta execute the ```detect_single_thread.py``` or ```detect_multi_thread.py``` in order to run the program.
```detector_utils.py``` is a utility function library.
