### ISSUE TITLE
How to load this model by java?

### ISSUE THREAD

**Issue by chandler1142** [victordibia/handtracking#48]
I just tested the handtrack.js performance, more or less about 5ps~8ps in my computer. I suspect the performance will be improved if I build a java server with strong compute ability node to handle the canvas image frame.
What a pity, I am not quite familiar with the tensorflow java api. Could you show me more about how to load pb file and manifest.json by java ? 
Thanks so much

**Comment by chandler1142** [comment]
I tried to load as below:
            SavedModelBundle model = SavedModelBundle.load("${mypath}\\ssdlitemobilenetv2\\frozen_inference_graph_141 14-51-46-798.pb", "serve");

and error as below:
org.tensorflow.TensorFlowException: SavedModel not found in export directory:

**Comment by chandler1142** [comment]
I have implemented the model recognition by java. However, I found it's slower than the js code...

**Comment by victordibia** [comment]
Glad you found a solution.
