### ISSUE TITLE
Find x and y position

### ISSUE THREAD

**Issue by Bealln** [victordibia/handtracking#49]
I would like to get the position of the centre of the hand. Is there an easy way to do this from your code? 

Thanks for the code! Great project

**Comment by victordibia** [comment]
Yes.
The output of the prediction is a bounding box represented by four points (topleft, topright, height and width). You can compute the center as topleft + width/2 and topright - height/2. This type of computation is used in the [skyfall](https://github.com/victordibia/skyfall) example and also handtrack.js ...

![image](https://user-images.githubusercontent.com/1547007/56871114-3b9cbb80-69e7-11e9-9113-3670a6c292ff.png)

I would suggest you take a look at the skyfall example frontend code  ...

**Comment by Bealln** [comment]
Hi!
I am really straddling to find this. There is not parameter called "topleft" or "width" in any of the codes.
