### ISSUE TITLE
How can I detect hands in Jpg?(panel disappeared & size) 

### ISSUE THREAD

**Issue by CtheLightt** [victordibia/handtracking#50]
I'd like to find hand in jpg, but if I use the repo(single-threaded), the processed panel appeared and disappeared immediately and it's not sized properly.
How can fix this?

**Comment by victordibia** [comment]
This is not an issue with the handtracking model ... more of an issue with how opencv is used to display images. See the following stackoverflow posts for some guidance.

https://answers.opencv.org/question/12129/why-the-image-just-disappears-in-the-following-code/
https://stackoverflow.com/questions/22274789/cv2-imshow-function-is-opening-a-window-that-always-says-not-responding-pyth
