### ISSUE TITLE
Just sending a note

### ISSUE THREAD

**Issue by zzeitt** [victordibia/handtracking#51]
Hello Dibia,

I have created a project based on your repo. Hope you know about it.

And it will be my pleasure if you add my project to the list.😀

> Here is the link to my project: [Gesture Recognition](https://github.com/zzeitt/Gesture-Recognition)

**Comment by victordibia** [comment]
Hi @zzeitt ,
Sorry for the late reply.
Amazing! Thanks for sharing, it looks well done!
Have added it to the list!!

-V.
