### ISSUE TITLE
Polygons are incorrectly used for BoundingBox calculation

### ISSUE THREAD

**Issue by GustavZ** [victordibia/handtracking#6]
Hey Victor,

i decided to open a new issue for that.

I changed the cv2.watkey() to 1000 to see each frame with polygons and bounding boxes.

It appears that the polygons are not correct for the adressed image frames.

Here are some screnshots which visualize the problem pretty well:
![screenshot from 2018-01-23 17-27-11](https://user-images.githubusercontent.com/29252883/35287683-3d909c8e-0063-11e8-8e34-33e7eed47be2.png)
![screenshot from 2018-01-23 17-26-51](https://user-images.githubusercontent.com/29252883/35287690-4234ceb8-0063-11e8-8f76-ca2d63157c18.png)
![screenshot from 2018-01-23 17-26-45](https://user-images.githubusercontent.com/29252883/35287695-455a6b98-0063-11e8-9033-b18bc36b8baa.png)

The Network wont be able to learn anything with that data,

Maybe this could be solved by sorting the images correctly befor feeding them into the `rename_files()` function! See this Thread: https://stackoverflow.com/questions/13122005/files-from-directory-being-pulled-in-wrong-order-with-python

Best,
Gustav

**Comment by victordibia** [comment]
Hi @GustavZ ,

Thanks for pointing these out, this feedback is quite insightful.

- The main reason the images and bounding boxes are visualized is to catch the exact sort of error you just showed. For some reason, the bounding boxes in your code run are incorrect. This is not the case on my end. Below is a link to the how the bounding box and polygon.mat is processed at my end.
ALL boxes are drawn correctly.
https://www.youtube.com/watch?v=PA0lBI_hp4w&feature=youtu.be
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/1547007/35289896-a23d9d26-0036-11e8-9e77-ec2e7c66d275.png">

- As to why bounding boxes are mismatched on your end, one thing I  notice immediately is  my tests are on a Mac (you are using Ubuntu). As you pointed out, it is possible that there are differences in how  python os code processes directories in Ubuntu vs Mac (I did not factor this in .. relatively new to python). I think the fix suggested by @csaldi in issue #3 should work. I.e sorting image_path array from in ascending order. My suspicion is that on a mac, the os directory walkthrough code  returns files in the sorted ascending order but does not do the same on Ubuntu. 

- I just [pushed a fix which sorts the image_path array](https://github.com/victordibia/handtracking/commit/f1a3fb3d7d2314863f6c9ead4ebead142af9d4de).  I dont have access to an ubuntu machine, but will try to do this over the next couple days.

Let me know if the fix works for you.

Thanks for the feedback!

-V.

**Comment by GustavZ** [comment]
Hey Victor,

that did the job! Great thanks!
I added sorted() to all os.listdir() functions, as they use arbitary order, just to make sure if there could be similar problems with other python / OS versions.

**Comment by victordibia** [comment]
Great!
Let me know how the results from training with both datasets go!

-V.
