### ISSUE TITLE
Oxford Dataset

### ISSUE THREAD

**Issue by GustavZ** [victordibia/handtracking#8]
Hey Victor,

do you have a script to convert the .mat files of the oxford dataset to .xml or .csv files?
I have one, but again i am not sure if the final annotations i get are correct, so i would like to crossvalidate with your solution.

**Comment by victordibia** [comment]
I have a [script](https://codepen.io/victordibia/pen/RxXwed) .. but its unlikely to be helpful in its current state (its not documented or well structured and I do not have time to do that at the moment).

The key is to `visualize` the annotations before you convert them to csv or xml.
Once you do this, the rest of the code I provide should provide some guidance (i.e the conversion to xml and csv).

best,
-V.

**Comment by awl-thanh-nguyen** [comment]
Hi @gustavz and @victordibia,
Could you share the script to convert the .mat files of the oxford dataset to .xml? The links above does not work. Thank you!

**Comment by edwardnguyen1705** [comment]
Hi @gustavz and @victordibia 
Could you share a script to convert the .mat files of the oxford dataset to .xml? The link above does not work. Thank you!
